export const permissionsCategorys = {
    administrative_permissions : "administrative_permissions",
    report_permissions:"report_permissions",
    summary_permissions:"summary_permissions",
    cashier_waiter_permissions:"cashier_waiter_permissions",
    other_permissions:"other_permissions",
    menu_permissions:"menu_permissions",
    inventory_permissions:"inventory_permissions",
    customer_permissions:"customer_permissions",
    order_permissions:"order_permissions",
    purchase_permissions:"purchase_permissions",
    role_permissions:"role_permissions",
    inventory_spot_permissions:"inventory_spot_permissions",
    count_sheet_permissions:"count_sheet_permissions",
    transfer_permissions:"transfer_permissions",
    transfer_order_permissions:"transfer_order_permissions",
    charges_permissions:"charges_permissions",
    kitchen_flow_permissions:"kitchen_flow_permissions",
    settings_permissions:"settings_permissions"
    }