export const arabicApplyOn = [
  'انتهاء تاريخ العمل للمخزون',
  'إرسال طلب شراء للمراجعة والموافقة',
  'إرسال معاملة تعديل تكلفة',
  'إرسال معاملة شراء',
  'إرسال معاملة جرد المخزون',
  'إرسال طلب تحويل للمراجعة',
  'إرسال معاملة إنتاج',
  'إرسال معاملة تعديل كميات',
  'إرجاع عناصر للمورّد',
  'إرسال عناصر مخزون من مستودع أو فرع',
  'وجود معاملة تحويل بانتظار الاستلام',
  'استلام عناصر المخزون من معاملة تحويل',
  'وصول عنصر المخزون إلى الحد الأقصى للكمية',
  'وصول عنصر المخزون إلى الحد الأدنى للكمية',
  'عدم توفر عنصر المخزون بعد الآن',
  'رفض مستخدم لعملية تحويل',
  'استلام عملية تحويل مع اختلاف في الكمية'
];

export const englishApplyOn = [
  'Inventory business date ends',
  'user submits a purchase order for review and needs approval',
  'user submits a cost adjustment transaction',
  'user submits a purchasing transaction',
  'user submits an inventory count transaction',
  'user submits a transfer order for review',
  'user submits a production transaction',
  'user submits a quantity adjustment transaction',
  'user returns items to a supplier',
  'user sends inventory items from a warehouse or branch',
  'there is a transfer transaction waiting to be received',
  'user receives inventory items from a transfer transaction',
  'inventory item reaches its maximum quantity level.',
  'inventory item reaches its minimum quantity level.',
  'inventory item is not available anymore',
  'user rejects a transfer',
  'user receives a transfer with a quantity variance.',
];