name: Auto Version & Publish to npm

on:
  push:
    branches:
      - main

jobs:
  version-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Bump version (patch)
        run: |
          npm version patch --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "chore: bump version"
          git push

      - name: Build the package
        run: npm run build
